// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_LayerGraphicsMZ","status":true,"description":"(v.1.3) Create graphic layers for parallax mapping, fog, etc. View documentation for plugin commands.","parameters":{"fixPosition":"true"}},
{"name":"ThaiFontAutoAdjuster","status":true,"description":"ปรับตัวอักษรภาษาไทยไปตามยถากรรม\nLicense: MIT License","parameters":{}},
{"name":"GALV_MessageTimerMZ","status":true,"description":"(v.1.2) Visual timer for messages and choices.","parameters":{"globalTimer":"0","timerHeight":"10","timerMaxWidth":"","timerPadding":"10","timerPos":"top","timerOffset":"0,0","timerColor1":"0,0,0,0.5","timerColor2":"255,255,255,1"}},
{"name":"GALV_MessageStylesMZ","status":true,"description":"(v.2.1) 'Show Text' windows float above characters and change visuals during game.","parameters":{"iIndicator":"2,0,-12","mPadding":"0,0,0,0","invertPos":"false","aGraphic":"WindowArrow","yOffset":"60"}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}}
];
